name = "base"
main = "index.js"
compatibility_date = "2025-10-19"

[[durable_objects.bindings]]
name = "HUB_OBJECT"
class_name = "HUB_OBJECT"

[observability]
[observability.logs]
enabled = false
head_sampling_rate = 1
invocation_logs = true
persist = true
